### PR TITLE
Issue-206: Hide Memo option for T address transaction

### PR DESCRIPTION
**Pull request by Mandeepbhalothia**

### CODE REVIEW

**Comment by Mandeepbhalothia** [comment]
@nighthawk24 @gmale Please review the PR.

**Comment by gmale** [comment]
I couldn't get to this today but I'll pick it up tomorrow.

**Review by gmale — APPROVED** [review]
This looks great. Since there was another PR for the same issue, I have combined both into #244. I take responsibility for any confusion so I've done the legwork of going through each commit and merging the code into one approach that works. I tried to take the best of both ideas and structure the merge so that you both get credit.

The only thing left is to test. Once that's complete, I'll merge to master and close all the PRs.

**Comment by gmale** [comment]
The changes in this PR have been integrated and merged here: https://github.com/zcash/zcash-android-wallet/pull/244

**Pull request merged**
