### PR TITLE
feature/change-server

### PR DESCRIPTION
**Pull request by gmale**
Adding the SDK portion to enable changing the server

Tasks:

- [x] migrate to the latest SDK
- [x] add the change server call into the right place
- [x] request design review of UI and respond to any feedback
- [x] request PR review from @nighthawk24 and respond to any feedback
- [ ] merge

### CODE REVIEW

**Comment by gmale** [comment]
Adjusted UI to respond to design feedback (note buttons also only enable when values have changed):

PREVIOUS
  

CURRENT

**Comment by gmale** [comment]
Hey @nighthawk24 I'm finally done with adding the settings changes. I'll repost my DM here so it's linked to the PR. It's cool working together on this, thanks so much for submitting the [initial PR](https://github.com/zcash/zcash-android-wallet/pull/203)!

> Hey Adi, I finally got this done by the end of this sprint. Sorry that it took a week. The trouble was that I was making significant changes on the SDK side and couldn't start work on the wallet until those things were done. I folded in the work of updating this screen into the work I did for the sprint.
>
>The SDK changes are done and merged as version 1.1.0-beta07
>https://github.com/zcash/zcash-android-wallet-sdk/pull/165
>
>The commit that added the ability to change servers is here:
>https://github.com/zcash/zcash-android-wallet-sdk/pull/165/commits/ab5b34cbd81a2c7d9d40f702fe1e206ddecfcab6
>
>The wallet changes are in this PR:
>https://github.com/zcash/zcash-android-wallet/pull/205
>
>The commit that added the settings updates is here:
> https://github.com/zcash/zcash-android-wallet/pull/205/commits/5e2f79ba623c3c8931850c2d60a01af8a5184d55
>
> I listed the main changes in the [full commit message](https://github.com/zcash/zcash-android-wallet/pull/205/commits/5e2f79ba623c3c8931850c2d60a01af8a5184d55).

**Comment by nighthawk24** [comment]
@gmale The code changes look good.
I was again unable to test the changes on a device as the updated beta07 sdk lib has not percolated through the maven system.

Here is the error:
Could not determine the dependencies of task ':app:compileZcashmainnetDebugJavaWithJavac'.
```
> Could not resolve all task dependencies for configuration ':app:zcashmainnetDebugCompileClasspath'.
   > Could not find cash.z.ecc.android:zcash-android-sdk-mainnet:1.1.0-beta07.
     Required by:
         project :app
```

**Comment by gmale** [comment]
@nighthawk24 I'm working through an issue with bintray/jcenter. Long story short, I tried to rename the repositories in bintray using their UI and it didn't work. I've sent like 7 emails back-and-forth with their support team and I think it will be resolved soon. In the meantime, you can use this workaround:

Add the bintray repo directly to `zcash-android-wallet/build.gradle`:

```groovy
allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven { url 'https://jitpack.io' }

       // ADD THIS ONE TO THE LIST:
        maven {
            url "https://dl.bintray.com/ecc-mobile/android"
        }
    }
}

```

**Comment by nighthawk24** [comment]
Oops, ran in to a crash when updating existing installation of ECC Wallet.

Environment: API 30 emulator

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cash.z.ecc.android, PID: 17335
    cash.z.ecc.android.sdk.exception.InitializerException$MissingViewingKeyException: Expected a viewingKey for this wallet but failed to find one. This usually means that wallet setup happened incorrectly. A workaround might be to derive the viewingKey from the seed or seedPhrase, if they exist, but it is probably better not to mask this error because the root issue should be addressed.
        at cash.z.ecc.android.ui.setup.WalletSetupViewModel$loadConfig$1$1.invoke(WalletSetupViewModel.kt:59)
        at cash.z.ecc.android.ui.setup.WalletSetupViewModel$loadConfig$1$1.invoke(WalletSetupViewModel.kt:26)
        at cash.z.ecc.android.sdk.Initializer$Builder.<init>(Initializer.kt:165)
        at cash.z.ecc.android.ui.setup.WalletSetupViewModel$loadConfig$1.invokeSuspend(WalletSetupViewModel.kt:57)
        at cash.z.ecc.android.ui.setup.WalletSetupViewModel$loadConfig$1.invoke(Unknown Source:10)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:60)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:210)
        at kotlinx.coroutines.flow.FlowKt__ReduceKt.single(Reduce.kt:147)
        at kotlinx.coroutines.flow.FlowKt.single(Unknown Source:1)
        at cash.z.ecc.android.ui.setup.WalletSetupViewModel.buildInitializer(WalletSetupViewModel.kt:53)
        at cash.z.ecc.android.ui.home.HomeFragment$onAttach$1.invokeSuspend(HomeFragment.kt:68)
        at cash.z.ecc.android.ui.home.HomeFragment$onAttach$1.invoke(Unknown Source:10)
        at cash.z.ecc.android.sdk.ext.FlowKt$onFirstWith$1$1.invokeSuspend(Flow.kt:48)
        at cash.z.ecc.android.sdk.ext.FlowKt$onFirstWith$1$1.invoke(Unknown Source:10)
        at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Collect.kt:134)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:73)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:55)
        at cash.z.ecc.android.ui.setup.WalletSetupViewModel$checkSeed$1.invokeSuspend(WalletSetupViewModel.kt:48)
        at cash.z.ecc.android.ui.setup.WalletSetupViewModel$checkSeed$1.invoke(Unknown Source:10)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:60)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:210)
        at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1.collect(SafeCollector.common.kt:114)
        at kotlinx.coroutines.flow.FlowKt__ReduceKt.first(Reduce.kt:163)
        at kotlinx.coroutines.flow.FlowKt.first(Unknown Source:1)
        at cash.z.ecc.android.sdk.ext.FlowKt$onFirstWith$1.invokeSuspend(Flow.kt:49)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:333)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:49)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at cash.z.ecc.android.sdk.ext.FlowKt.onFirstWith(Flow.kt:46)
        at cash.z.ecc.android.ui.home.HomeFragment.onAttach(HomeFragment.kt:60)
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:2894)
        at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:485)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:269)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2173)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2089)
E/AndroidRuntime:     at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1985)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3119)
        at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:3046)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2960)
        at androidx.fragment.app.FragmentStateManager.ensureInflatedView(FragmentStateManager.java:413)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:275)
        at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:133)
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:313)
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:292)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1067)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
        at cash.z.ecc.android.ui.MainActivity.onCreate(MainActivity.kt:112)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

**Comment by gmale** [comment]
The crashes that were seen here were [fixed in this commit](https://github.com/zcash/zcash-android-wallet/pull/207/commits/a693caf49970abc3ab0e13d33b2c9c921e3b0131) by patching the underlying secure storage library and then iterating on the way the app uses storage. Main takeaway: we should probably move to the secure storage library from google that is most ready. Both of the available options are still in alpha and are missing key features. Hopefully, the new [DataStore library](https://android-developers.googleblog.com/2020/09/prefer-storing-data-with-jetpack.html) adds encryption support sometime soon. There is an [open feature request](https://issuetracker.google.com/issues/167697691) for it with 22 stars. So hopefully, it happens soon.

**Comment by gmale** [comment]
> the updated beta07 sdk lib has not percolated through the maven system.

The maven issues have also been resolved. It should no longer be necessary to add the bintray repo, directly. The final artifact ID is: [cash.z.ecc.android:zcash-android-sdk-mainnet](https://github.com/zcash/zcash-android-wallet/issues/202)

**Pull request merged**
