### PR TITLE
Implement autoshielding UI prompt

### PR DESCRIPTION
**Pull request by ccjernigan**

### CODE REVIEW

**Comment by pacu** [comment]
I just realized #269 is poorly defined. Maybe you did this or maybe not. Don't worry.

on iOS when there are transparent funds over 0.01 ZEC the "awesome do it" button proceeds to shield those funds and show the _shielding_ animation screen and the success or error feedback.

**Comment by ccjernigan** [comment]
No, I did not do this. But I can add it.

In addition to checking for funds and displaying the shielding screen, I believe I'll have to wait for the initial download to complete before displaying the popup in the first place.

**Comment by pacu** [comment]
That would be great! thanks

**Review by pacu — CHANGES_REQUESTED** [review]
Carter will modify the code to appear once the app is synced and trigger a manual shielding if needed

**Review by pacu — APPROVED** [review]

**Comment by ccjernigan** [comment]
I finished manually testing this with the testnet and can confirm the information prompt will successfully take the user through the shielding flow if there are enough funds.

@pacu I added one commit since your last review, adjusting the threshold for autoshielding from `> 1` to `>= 1` since otherwise this is difficult to test on the testnet.

I also found a pre-existing issue in the way we display the autoshielding prompt, which I filed as #288.

**Pull request merged**
